dns:
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  direct-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter: []
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fallback: []
  fallback-filter:
    domain: []
    geoip: false
    geoip-code: ""
    ipcidr: []
  ipv6: true
  listen: 127.0.0.1:53
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  nameserver-policy: {}
  prefer-h3: false
  proxy-server-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  respect-rules: true
  use-hosts: true
  use-system-hosts: false
hosts: {}
